version: "3"

services:
    php:
        image: adhub.azurecr.io/acho:Empty
        working_dir: /ad-hub.net/apps
        restart: always
        stop_grace_period: 60s
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./scripts/docker-entrypoint-init.sh:/docker-entrypoint-init.sh
            - /etc/letsencrypt:/etc/letsencrypt
            - /ad-hub.net/media:/ad-hub.net/media
            - /ad-hub.net/apps:/ad-hub.net/apps
            - ./scripts:/etc/acho-scripts
            - ./config:/etc/service-configs
            - ./config/acho-java/${VMSS_ENV:-dev}:/etc/acho-java
            - ./config/nginx/sites-available/${VMSS_ENV:-dev}:/etc/nginx/sites-enabled
            - ./config/supervisor.d/${VMSS_ENV:-dev}:/etc/supervisor/conf.d
        environment:
            - LANG=C.UTF-8
            - ENABLE_CROND=${ENABLE_CROND:-no}
            - VMSS_ENV=${VMSS_ENV:-dev}
        extra_hosts:
            - "acho-localhost:127.0.0.1"
            - "vmss-external-server:<EXTERNAL_SERVER_IP>"
