kind: Service
apiVersion: v1
metadata:
  name: acho-web-service
spec:
  loadBalancerIP: 13.78.65.111
  type: LoadBalancer
  ports:
    - name: www
      port: 80
      targetPort: 80
  selector:
    app: acho
    type: web